### check server
GET http://localhost:3000/status

### profile route
GET http://localhost:3000/profile

### login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "123",
    "password": "123"
}